name: Build plugin

on: [push, workflow_dispatch]

env:
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  ONSHAPE_OAUTH_CLIENT_ID: ${{ secrets.ONSHAPE_OAUTH_CLIENT_ID }}
  ONSHAPE_OAUTH_SECRET: ${{ secrets.ONSHAPE_OAUTH_SECRET }}

jobs:
  build-plugin:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Add mask to hide secrets
        run: echo "::add-mask::${{ secrets.ENCRYPTION_KEY }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Create authentication file
        run: python .github/workflows/make_secrets.py

      - name: Insert decryption key
        run: sed -i 's/__ENCRYPTION_KEY__/${{ secrets.ENCRYPTION_KEY }}/g' src/OAuthController.py

      - uses: fieldOfView/cura-plugin-packager-action@main
        with:
          source_folder: "."
          package_info_path: ".github/workflows/package.json"

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: ./*.curapackage
          retention-days: 10
